# Generated by Django 2.0.3 on 2018-03-30 22:34

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_news_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news_item',
            options={'verbose_name': 'News Item'},
        ),
        migrations.AlterField(
            model_name='news_item',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='news_item',
            name='title',
            field=models.CharField(max_length=350, unique=True, verbose_name='Title'),
        ),
    ]
