# Generated by Django 2.0.3 on 2018-04-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20180330_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab_member',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv/', verbose_name='CV'),
        ),
    ]
